language: php
php:
  - '8.0'
  - '8.1'

before_install:
  - export COMPOSER_MEMORY_LIMIT=-1
install: composer install

script: vendor/bin/phpunit

branches:
  except:
    - staging-test

notifications:
  email:
    recipients:
      - sdk_developers@cloudinary.com
